apiVersion: v1
kind: ServiceAccount
metadata:
  name: knot-eso
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: knot-vault
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "knot"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "knot"
          serviceAccountRef:
            name: knot-eso
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: knot-web-secrets
spec:
  secretStoreRef:
    name: knot-vault
    kind: SecretStore
  target:
    name: knot-web-secrets
  refreshInterval: 1h
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: web
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: web
        property: JWT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: knot-postgres-secrets
spec:
  secretStoreRef:
    name: knot-vault
    kind: SecretStore
  target:
    name: knot-postgres-secrets
  refreshInterval: 1h
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: POSTGRES_PASSWORD
