apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knot-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - knot.monashautomation.com
      secretName: knot-web-tls
  rules:
    - host: knot.monashautomation.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: knot-web
                port:
                  number: 80
