apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-deployment.yaml
  - migration-job.yaml
  - postgres.yaml
  - external-secrets.yaml
  - ingress.yaml
  - configmap.yaml
